### ISSUE TITLE
Images for collections documentation

### ISSUE THREAD

**Issue by joelarencibiar** [cenit-io/docs#49]

**Comment by AnaCenit** [comment]
![Collections Menu](https://user-images.githubusercontent.com/99367633/159567476-f56cdd59-9b6f-49af-b5fc-586a6d602381.png)

**Comment by AnaCenit** [comment]
![Reviewing a connection](https://user-images.githubusercontent.com/99367633/159568976-11ce28b2-8012-45bc-80b6-759843902212.png)

**Comment by AnaCenit** [comment]
![Adding a new Collection](https://user-images.githubusercontent.com/99367633/159572522-38170c7c-a4f6-4a9c-aabb-9a53b887a31a.png)

**Comment by AnaCenit** [comment]
![Pasting a datatype in a new collection](https://user-images.githubusercontent.com/99367633/159576230-d64b3dc0-e2ae-4fc7-9f64-faf84cdd3856.png)

**Comment by AnaCenit** [comment]
![Uploading Checking system notifications when creating a collection.png…]()

**Comment by AnaCenit** [comment]
![Checking system notifications when creating a collection](https://user-images.githubusercontent.com/99367633/159578267-c4fafec4-be49-4f07-b543-05732ce4780b.png)

**Comment by AnaCenit** [comment]
![Sharing a collection first picture](https://user-images.githubusercontent.com/99367633/159581031-9b5689a7-62aa-4621-905b-198192ce6bb3.png)

**Comment by AnaCenit** [comment]
![Sharing a collection second picture](https://user-images.githubusercontent.com/99367633/159582932-bf113cdd-9eef-4f83-9fde-b1a63b46f77f.png)

**Comment by AnaCenit** [comment]
![Import Operation](https://user-images.githubusercontent.com/99367633/159703223-dc53acb3-272d-4b5d-8649-3f5f7720196b.png)

**Comment by AnaCenit** [comment]
![Upload a collection in json format](https://user-images.githubusercontent.com/99367633/159712803-f07aabc8-9a22-4c13-a877-c1019b4737db.png)

**Comment by AnaCenit** [comment]
![Administrator Menu](https://user-images.githubusercontent.com/99367633/160730468-0c065cb7-e7f7-44ee-8bdc-92b785d2664f.png)

![tenants](https://user-images.githubusercontent.com/99367633/160722661-e9946e33-6d71-446b-abea-08ddb2d652a9.png)

![my tenant](https://user-images.githubusercontent.com/99367633/160723760-be762e28-6f43-4639-b931-e9ea7acf96e7.png)

**Comment by AnaCenit** [comment]
![New record](https://user-images.githubusercontent.com/99367633/160859615-319e5a3b-1371-4504-a453-408356e7508d.png)

![Records of data type](https://user-images.githubusercontent.com/99367633/160858821-b289a8be-751a-4bb2-9af9-88e672dd5de2.png)

![Schema](https://user-images.githubusercontent.com/99367633/160854356-a993c604-288e-4f05-af26-34f0d21a2c64.png)

![Details of data type](https://user-images.githubusercontent.com/99367633/160853756-dc718d95-25ae-4d58-8478-79f42820fb4e.png)

![Managing a data type](https://user-images.githubusercontent.com/99367633/160853166-2a83ba28-8bd8-4e1a-bb36-3078d6d1df43.png)

![List of data types](https://user-images.githubusercontent.com/99367633/160852366-fc4d5f02-52da-4fe4-b092-2e8325d47342.png)

![Snippets in datatypes](https://user-images.githubusercontent.com/99367633/160851634-69338726-35ca-492d-a812-285427428f6b.png)

![Data type in json](https://user-images.githubusercontent.com/99367633/160851004-fb2bffd8-7262-4334-9c85-0217e1a7760c.png)

![Adding document type](https://user-images.githubusercontent.com/99367633/160850550-178dbe58-a573-47df-8764-01af1c7b309a.png)


![Menu Data](https://user-images.githubusercontent.com/99367633/160849721-06e99859-5b8f-455b-a601-4283a0b3d464.png)

**Comment by AnaCenit** [comment]
![Test AnaPrueba](https://user-images.githubusercontent.com/99367633/160914181-43d09075-10d2-4044-b3f5-58337a55839f.png)

![Authorized!](https://user-images.githubusercontent.com/99367633/160913708-1473291c-a7d1-4a58-8da4-da3a222b334e.png)

![Test passed](https://user-images.githubusercontent.com/99367633/160913168-331bbc61-7244-45fc-a568-3a3888722e0b.png)

![Permitir](https://user-images.githubusercontent.com/99367633/160912769-0da08549-3d48-4780-8252-015747076b60.png)

![Slack Workspaces](https://user-images.githubusercontent.com/99367633/160911760-91f5ad4c-2886-4b39-8847-8e17a82d2be6.png)

![Slack](https://user-images.githubusercontent.com/99367633/160911280-ff7ae61b-4b2f-4e38-8112-e4c1c1330155.png)

![Redirect](https://user-images.githubusercontent.com/99367633/160910459-0592a761-78e7-4d3c-be3d-506babd2b375.png)

![Pressing authorize](https://user-images.githubusercontent.com/99367633/160909960-78a4c193-cc0f-4cfa-822c-5af2fb817371.png)

![New authorization](https://user-images.githubusercontent.com/99367633/160909212-9a328b46-4ebf-4522-a251-c533d999840c.png)

![Unauthorized](https://user-images.githubusercontent.com/99367633/160908843-0ad662d0-6006-4b58-ad76-ac67529e047f.png)

![Authorization view](https://user-images.githubusercontent.com/99367633/160908216-eff84249-5a46-4d64-a7ca-a16594cb748f.png)


![Scopes all](https://user-images.githubusercontent.com/99367633/160904274-5ce45343-c683-4daa-8c2c-80973144884d.png)

![Adding scopes](https://user-images.githubusercontent.com/99367633/160903272-43db7587-8b0e-4ed0-811b-c656f87512fe.png)

![Selecting client](https://user-images.githubusercontent.com/99367633/160902427-a2975a5d-9e65-41f3-bc67-63a3c63fdef0.png)

![Pick Authorization](https://user-images.githubusercontent.com/99367633/160901804-038de6b9-622c-4521-bc22-f32d945b1603.png)

![Add Authorization](https://user-images.githubusercontent.com/99367633/160901377-82f7f9f2-b707-4a4d-a064-da91464b2e60.png)

![Security Menu](https://user-images.githubusercontent.com/99367633/160885428-634bfb3f-e79a-41fd-aab3-a0d61bf5bdaa.png)

![Manage provider](https://user-images.githubusercontent.com/99367633/160884263-8bd5f809-c6cd-4f66-b2e0-c0afd5bdf860.png)

![Pick a provider](https://user-images.githubusercontent.com/99367633/160883401-f097cf70-e547-4553-9ccf-3d06e5ab9ee8.png)

![Adding a provider](https://user-images.githubusercontent.com/99367633/160882988-c227ba73-2ecb-4460-9d7b-033d8e108ad1.png)

![Manage clients](https://user-images.githubusercontent.com/99367633/160880483-f64d362d-5bc4-4049-b81b-06291dd64709.png)

![List of clients](https://user-images.githubusercontent.com/99367633/160879800-1a015394-2e27-434d-806c-aaff4a558a21.png)

![Setting the provider](https://user-images.githubusercontent.com/99367633/160879399-45d1dee9-e4d8-40cf-a284-e1a4b1d78ed6.png)

![List of providers](https://user-images.githubusercontent.com/99367633/160878059-436c0b93-0061-48e1-937e-dab1fa836470.png)

![Provider to Slack](https://user-images.githubusercontent.com/99367633/160876680-ba14bfad-7241-4cd7-bef7-ff660504f5e3.png)

![Token endpoint](https://user-images.githubusercontent.com/99367633/160876242-d90fdf3d-d917-47e0-89ed-c95499184478.png)

![Provider to Slack](https://user-images.githubusercontent.com/99367633/160875088-a7401b57-06c1-4b81-b552-8677816047e9.png)

![New authorization client](https://user-images.githubusercontent.com/99367633/160873693-27dfc56a-2f0c-4c31-ac10-7234796c8294.png)

![New authorization client](https://user-images.githubusercontent.com/99367633/160873169-a84d86dc-7320-43cd-829a-9801314ae214.png)

![New Connection](https://user-images.githubusercontent.com/99367633/160868810-19f81d85-fb81-4fe2-ad71-ac689081df83.png)

![New connection in the list](https://user-images.githubusercontent.com/99367633/160867928-ddecb031-836a-4b05-a412-b67893efd378.png)

![Save connection](https://user-images.githubusercontent.com/99367633/160866429-121df7d8-0076-425c-9a40-da8c1ac7a8ba.png)

![Authorization](https://user-images.githubusercontent.com/99367633/160865430-2e20a055-971d-425e-86a5-688a44fddf3e.png)

![First elements](https://user-images.githubusercontent.com/99367633/160863798-6b904c6c-3841-480a-8e88-9634dfec5b4b.png)

![Connection elements](https://user-images.githubusercontent.com/99367633/160863200-76125513-57b4-4027-9546-8e2dcf2e8cfc.png)

![New Connection](https://user-images.githubusercontent.com/99367633/160862728-d1c08859-c6e7-4f7f-bf9d-c02a91140e37.png)

![New File Type](https://user-images.githubusercontent.com/99367633/160861745-a9c6e9bd-801a-44de-ad04-17ed3439cfde.png)

![File Types](https://user-images.githubusercontent.com/99367633/160861178-cacebc38-c334-4871-be0f-25d4423eadc1.png)

**Comment by AnaCenit** [comment]
![New flow](https://user-images.githubusercontent.com/99367633/161121860-f59b0519-7f10-4ae1-8340-e65ded28a2c1.png)

![Process completed](https://user-images.githubusercontent.com/99367633/161118677-9c686571-75e4-485e-b8c4-41fdba7b8b60.png)

![Flows executed](https://user-images.githubusercontent.com/99367633/161116995-c9f4eb16-487f-43d0-b87e-b1514772139f.png)

![Send a record to a flow](https://user-images.githubusercontent.com/99367633/161111135-7da2c517-effb-4218-a8d2-765448f55cb6.png)

![Send to flow](https://user-images.githubusercontent.com/99367633/161110529-1f2f106b-cd2c-4bf0-9e5d-0d4e58b57328.png)

![Processing a flow](https://user-images.githubusercontent.com/99367633/161106867-ccd5d7bb-726a-4ef7-8b51-9284456f29d2.png)

![Process a flow](https://user-images.githubusercontent.com/99367633/161106351-98b8d114-0b67-4fe6-b154-b2eea984352e.png)

![New flow added](https://user-images.githubusercontent.com/99367633/161105195-191ade85-09a3-40a2-8510-447501c058cb.png)

![Selecting a translator](https://user-images.githubusercontent.com/99367633/161095063-1668949c-7750-48b1-b77c-04f5ad17ba8c.png)

![Data events](https://user-images.githubusercontent.com/99367633/161083716-bec39f20-d24f-450a-83ea-6fe4c6314b60.png)

![Menu Workflows](https://user-images.githubusercontent.com/99367633/161071948-7238d99d-7c01-4527-bd96-f5bcc2c67b7f.png)
